### ISSUE TITLE
docs: append an example in documentation with "endpoint_arguments_constructor" argument

### ISSUE THREAD

**Issue by harobed** [inveniosoftware/flask-breadcrumbs#17]
Append an example in documentation with "endpoint_arguments_constructor" argument (http://flask-breadcrumbs.readthedocs.org/en/latest/#flask.ext.breadcrumbs.register_breadcrumb)

**Comment by jirikuncar** [comment]
Similar to @snorfalorpagus question in #16.

**Comment by harobed** [comment]
Thanks.
