### ISSUE TITLE
Update documentation with an example of using MethodViews and blueprints.

### ISSUE THREAD

**Issue by nicholasRutherford** [inveniosoftware/flask-breadcrumbs#23]
After spending some time figuring it out, I made a small example of using flask-breadcrumbs with MethodViews and blueprints. It can be found here:

https://gist.github.com/nicholasRutherford/6a3db68e51108f6d1a44

If you think it is appropriate, could you add this example to the documentation?

**Comment by tiborsimko** [comment]
Can you please prepare a PR?

**Comment by jirikuncar** [comment]
> https://gist.github.com/nicholasRutherford/6a3db68e51108f6d1a44

It looks good :+1: . Thanks!
