### ISSUE TITLE
ExtDeprecationWarning: Importing flask.ext.menu is deprecated, use flask_menu instead

### ISSUE THREAD

**Issue by hieu-n** [inveniosoftware/flask-breadcrumbs#29]
With the new flask release (0.11), `flask.ext` is now deprecated. Most flask extensions have made the change.

This is not really an issue now, but it should be changed in future releases. I hope you guys do not mind me reporting this.

Cheers!

**Comment by jirikuncar** [comment]
@hieu-n we are aware of it. We are planning new release in upcoming days.
